/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BookingManager } from "./BookingManager";
export type { ChargingStationManager } from "./ChargingStationManager";
export type { JourneyPlanner } from "./JourneyPlanner";
export type { VehicleRegistry } from "./VehicleRegistry";
